name: educanet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_snack_bar: ^0.4.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.9.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_barcode_listener: ^0.1.4
  flutter_local_notifications: ^16.3.0
  flutter_spinkit: ^5.2.0
  get: ^4.6.6
  http: ^1.2.1
  intl: ^0.19.0
  permission_handler: ^11.1.0
  qr_code_scanner: ^1.0.1
  rxdart: ^0.28.0
  shared_preferences: ^2.2.2
  table_calendar: ^3.1.2
  visibility_detector: ^0.4.0+2
  awesome_notifications: ^0.9.3+1
  reactive_forms: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
