// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKSkG-6Ftg8yM_Ez69H3LYj0NdKqkbmVM',
    appId: '1:816592384727:web:0771dc688540f372b13692',
    messagingSenderId: '816592384727',
    projectId: 'educanet-70549',
    authDomain: 'educanet-70549.firebaseapp.com',
    storageBucket: 'educanet-70549.appspot.com',
    measurementId: 'G-8KK02N4G0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs6VaxWLD6TXm-GL5yBMGvJ56k1O0NQmk',
    appId: '1:816592384727:android:f284984d4dbabd06b13692',
    messagingSenderId: '816592384727',
    projectId: 'educanet-70549',
    storageBucket: 'educanet-70549.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRflS4Mt4gxGCIWCdK-788J66fJax_v7Y',
    appId: '1:816592384727:ios:7e2fffbdb3f0f0c9b13692',
    messagingSenderId: '816592384727',
    projectId: 'educanet-70549',
    storageBucket: 'educanet-70549.appspot.com',
    iosBundleId: 'com.instantdigital.educanet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKSkG-6Ftg8yM_Ez69H3LYj0NdKqkbmVM',
    appId: '1:816592384727:web:77b5afd6905ace24b13692',
    messagingSenderId: '816592384727',
    projectId: 'educanet-70549',
    authDomain: 'educanet-70549.firebaseapp.com',
    storageBucket: 'educanet-70549.appspot.com',
    measurementId: 'G-5GRX0N9QP5',
  );

}